txt = """
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
"""


txt = open('2025/day/07/input.txt').read()


txt = txt.strip()
arr = [list(l) for l in txt.split('\n')]

r = 0
for i in range(1, len(arr)):
    for j in range(len(arr[0])):
        if arr[i-1][j] == 'S' and arr[i][j] == '.':
            arr[i][j] = '|'
        if arr[i-1][j] == '|' and arr[i][j] == '.':
            arr[i][j] = '|'
        if arr[i-1][j] == '|' and arr[i][j] == '^':
            r += 1
            if j > 0 and arr[i][j-1] == '.':
                arr[i][j-1] = '|'
            if j < len(arr[i]) - 1 and arr[i][j+1] == '.':
                arr[i][j+1] = '|'


print(r)
