txt = """
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
"""

from functools import cache

arr = open('2025/day/07/input.txt').readlines()

@cache
def browse(i, j):
    if i == len(arr) - 1: return 1
    i += 1
    return browse(i, j-1) + browse(i, j+1) if arr[i][j] == '^' else browse(i, j)

print(browse(1, 70))
